os:
  - linux
services:
  - docker
language: java
node_js:
  - '10.16.3'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=10.16.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
before_install:
  - echo '*** Using OpenJDK 11 by default'
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update
  - sudo apt install openjdk-11-jdk
  - sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
  - java -version
  - sudo apt-get install python3
  - pip install awscli --upgrade --user
  - pip install awsebcli --upgrade --user
  - sudo apt-get install docker
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
install:
  - npm install
script:
  - chmod +x mvnw
  - ./mvnw -ntp clean verify
  - ./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run test-ci' -Dmaven.repo.local=$MAVEN_USER_HOME
  - ./mvnw -ntp verify -Pprod -DskipTests
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - npm run test
  - ./mvnw -ntp  org.jacoco:jacoco-maven-plugin:prepare-agent install  sonar:sonar
addons:
  sonarcloud:
    organization: 'senrokai-github'
    token:
      secure: 'I/wL5yd23iEr7/HXnCbfhd+lQVjEIqmcZAuVaiv/00xM/KWBLhodu7pAVSDTXhmRiTCuqkb+OxGo/M6MytJrZJc/XKzW8g7OtiBBN3M2gIfbfWiT02SA6RqBKEz3gbImEC5ahqVOEFTEhIXEQbfk03FeJTc5HiNmr+F8QIQVnEgYqcG6WZwubnM/Df6aR/KOWZcV9oaA6ZJgkrJqaDg5lxT/kjF5zm4YFmpGYlAzlRBmCzrvPoGhd4SCUKJ0Ca GousgF6fsrWbBhoWIC7B5ePQsOZBX8ODbZ2zGgTQbeCRqB5QRq9IGQAa+9UoEgHhRUmmaf8qPfKAFnjqxKwLTIzsyc9xcw+25EI/bxL/ui5vC1yo+F0nPTluB+S6qb4oUKCgLR1oPyjFbrax6Xo0W9s4tkgqV6Z77VWzI9wxI8Yla4m4ydIPb2XLWJaKUfG8cCGRxbBp8/M/KNaN+gpzJ0egSDQT2t3RGur0CS9Wi6sMLUvCR1yfyMbeWC+cdFH2A1m83o6mvqlZ0Bs0UeYIvloaXTydv22YF7Jyk23zk1jgrMSN/9nbkyWdfM3e5lqU8So2CYt/6Mnf2SY1e7cIpBqnw6DSJNkkDRn36e48a6fzier5zaQZUWqh6bPrXoWW6bogCTHofwIX/0QVpuouYK1Kytz13xNFH36fBeRfsDzcY='
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIATUADIRQAGNTL2YGH
  secret_access_key:
    secure: oWYhFM2cptMKx4ilPOekvRRu4sPmr/WI4w+L8tg0z9xtlboXVHsMD5v3Vx0pViwl9j5mgjRmDfwhtYvH+J91//LdbakMgkeqPvwwjYtZR4jIk4sVmBgeJOjcakcP/V8XhvV17H5+4Gs2sMiVRfCU6Tw2RvXlYA829PpPdUUZ+dzyZ2go6hNG/G1b6pbiGex8kryEUfW5ObOeYB15J/9Ccv2bovbKIxE0k+Hpmmr/zjywFde1EPLfSR2+3k3hvcC49pK/wmtzprLeBf6jPgTCjvSWrc0s462heoW+1S/85NzWZJw2jVD348EKrJeeQhM0xl3FRU1xfBXj48qI0nOsDk2O/R+rAc2/4j8OSVcpdVTP63Rec4KkXmTR7TA2LXVmr5z2/i+hqfF6WhCWBLBBPcrrjNjcQYfZ1oYPCs36iqXYbaWRtpcXyqxEuVgRmzAvtWVzkYCcOFQWmaKmwYpbe8VVykfwMzlPBxTHEuoECrvCJfto+v9Te/V9CY1w6PB9zUVQIeiP2MWBWzBSUAML6ZklZMR/t91RtnzI8CL8FC4N4DZ8YjedA7nRNvv2xHAYryEMzsnXua+QfIlmhuXNBqkk/BdElV30afPwWuSAK7jQOVSg8iAqipPTCWWylijFHzntYkzel5xiHJN8jLrvTm5NfF5ifEYhA1KqNDwdTCo=
  region: eu-west-1
  app: gifu-application
  env: GifuApplicationEnv
  on:
    repo: Coffee-GiFu/gifu-application
    branch: master
