os:
  - linux
services:
  - docker
language: java
node_js:
  - '10.16.3'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=10.16.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
before_install:
  - echo '*** Using OpenJDK 11 by default'
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update
  - sudo apt install openjdk-11-jdk
  - sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
  - nvm install $NODE_VERSION
  - npm install -g npm
  - chmod +x mvnw
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm run test-ci
        - ./mvnw -ntp org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - stage: deploy dev
      script:
        - sudo apt-get install python3
        - pip install awsebcli --upgrade --user
        - echo $DOCKER_PASSWORD | docker login -u AWS --password-stdin https://249114954752.dkr.ecr.eu-west-1.amazonaws.com
        - eb init --platform "arn:aws:elasticbeanstalk:eu-west-1::platform/Docker running on 64bit Amazon Linux/2.12.17"
        - ./mvnw -ntp package verify -DskipTests jib:dockerBuild
        - docker tag gifu-dev:$VERSION 249114954752.dkr.ecr.eu-west-1.amazonaws.com/gifu-backend-dev:$VERSION
        - docker push 249114954752.dkr.ecr.eu-west-1.amazonaws.com/gifu-backend-dev:$VERSION
        - eb deploy GifuApplicationEnv
    #    - script:
    #        - docker build -f ./docker_front/Dockerfile-dev -t gifu-frontend-dev:$VERSION .
    #        - echo $GITHUB_PASSWORD | docker login -u Senrokai --password-stdin docker.pkg.github.com
    #        - docker tag gifu-frontend-dev:$VERSION docker.pkg.github.com/coffee-gifu/gifu-application/gifu-frontend-dev:$VERSION
    #        - docker push docker.pkg.github.com/coffee-gifu/gifu-application/gifu-frontend-dev:$VERSION
    #        - DOCKER_HOST=ec2-34-241-150-218.eu-west-1.compute.amazonaws.com:2376 docker stack deploy --compose-file ./docker_front/docker-compose.dev.yml gifu-frontend-dev
    - stage: deploy prod
      script:
        - sudo apt-get install python3
        - pip install awsebcli --upgrade --user
        - eb init --platform "arn:aws:elasticbeanstalk:eu-west-1::platform/Docker running on 64bit Amazon Linux/2.12.17"
        - echo $DOCKER_PASSWORD | docker login -u AWS --password-stdin https://249114954752.dkr.ecr.eu-west-1.amazonaws.com
        - ./mvnw -ntp package -Pprod verify -DskipTests jib:dockerBuild
        - docker tag gifu-backend:$VERSION 249114954752.dkr.ecr.eu-west-1.amazonaws.com/gifu-backend:$VERSION
        - docker push 249114954752.dkr.ecr.eu-west-1.amazonaws.com/gifu-backend:$VERSION
        - eb deploy GifuApplication-prod
stages:
  - test
  - name: deploy dev
    if: branch = develop
  - name: deploy prod
    if: branch = master
addons:
  sonarcloud:
    organization: 'senrokai-github'
    token:
      secure: 'I/wL5yd23iEr7/HXnCbfhd+lQVjEIqmcZAuVaiv/00xM/KWBLhodu7pAVSDTXhmRiTCuqkb+OxGo/M6MytJrZJc/XKzW8g7OtiBBN3M2gIfbfWiT02SA6RqBKEz3gbImEC5ahqVOEFTEhIXEQbfk03FeJTc5HiNmr+F8QIQVnEgYqcG6WZwubnM/Df6aR/KOWZcV9oaA6ZJgkrJqaDg5lxT/kjF5zm4YFmpGYlAzlRBmCzrvPoGhd4SCUKJ0Ca GousgF6fsrWbBhoWIC7B5ePQsOZBX8ODbZ2zGgTQbeCRqB5QRq9IGQAa+9UoEgHhRUmmaf8qPfKAFnjqxKwLTIzsyc9xcw+25EI/bxL/ui5vC1yo+F0nPTluB+S6qb4oUKCgLR1oPyjFbrax6Xo0W9s4tkgqV6Z77VWzI9wxI8Yla4m4ydIPb2XLWJaKUfG8cCGRxbBp8/M/KNaN+gpzJ0egSDQT2t3RGur0CS9Wi6sMLUvCR1yfyMbeWC+cdFH2A1m83o6mvqlZ0Bs0UeYIvloaXTydv22YF7Jyk23zk1jgrMSN/9nbkyWdfM3e5lqU8So2CYt/6Mnf2SY1e7cIpBqnw6DSJNkkDRn36e48a6fzier5zaQZUWqh6bPrXoWW6bogCTHofwIX/0QVpuouYK1Kytz13xNFH36fBeRfsDzcY='
