version: '2'
services:
  gifu-backend:
    image: gifu
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8888:8888
