version: '2'
services:
  gifu-backend:
    image: gifu-backend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gifu-postgresql:5432/Gifu
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8888:8888
  gifu-postgresql:
    extends:
      file: postgresql.yml
      service: gifu-postgresql
