version: "3.0"
services:
  react:
    build: .
    image: docker.pkg.github.com/coffee-gifu/gifu-application/gifu-frontend
    deploy:
      labels:
        - "traefik.http.routers.react.rule=Host(`gifu.boostercamp-frontend.soat-sandbox.aws.soat.fr`)"
        - "traefik.http.services.react.loadbalancer.server.port=80"
        - "traefik.enable=true"
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.2"
          memory: 128Mi
        reservations:
          cpus: '0.2'
          memory: 128Mi
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

