FROM node:12-alpine  as build-stage
WORKDIR /app
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY .eslintrc.json .
COPY .eslintignore .
COPY postcss.config.js .
RUN  npm install
COPY webpack webpack/
COPY src/main/webapp/ src/main/webapp/
RUN npm run webpack:prod

FROM nginx:alpine
COPY --from=build-stage /app/target/classes/static /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
